P7/urls.py
from django.contrib import admin
from django.urls import path,include
from myapp import views
import myapp
urlpatterns = [
    path('admin/', admin.site.urls),
    path('page1/',views.page1,name="page1"),
    path('page2/',views.page2,name="page2"),
    path('',include('myapp.urls')),
]

myapp/urls.py
from django.urls import path
from myapp import views
app_name="myapp"
urlpatterns=[
    path('topics/',views.topic,name="topic"),
    path('records/',views.records,name="records"),
    path('page5/',views.page5,name='forms'),
    path('display/',views.display,name="display"),
]

myapp/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
    topic=models.CharField(primary_key=True,max_length=20)

    def __str__(self):
        return self.topic

class Webpage(models.Model):
    topic=models.ForeignKey(Topic,on_delete=models.CASCADE)
    name=models.CharField(primary_key=True,max_length=50)
    url=models.CharField(unique=True,max_length=50)
    
    def __str__(self):
        return self.name

class Access_Records(models.Model):
    name=models.ForeignKey(Webpage,on_delete=models.CASCADE)
    date=models.DateField()

    def __str__(self):
        return str(self.date)

myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from myapp.models import *
# Create your views here.

def page1(request):
    return HttpResponse("<h1>welcome to page 1</h1>")

def page2(request):
    return render(request,'page2.html',context={'data':"data is passed"})

def topic(request):
    d={'objects':Topic.objects.all()}
    return render(request,'page3.html',context=d)

def records(request):
    d={'objects':Access_Records.objects.order_by('date')}
    return render(request,'page4.html',context=d)

def page5(request):
    data=Topic.objects.all()
    return render(request,'page8.html',context={'objects':data})

def display(request):
    print(request.POST)
    #print(request.POST['topic'])
    topics=Topic.objects.all()
    qs=Webpage.objects.none()
    for top in topics:       
        if top.topic in request.POST:
            data=request.POST.get(top.topic,"Key not found")
            qs=qs.union(Webpage.objects.all().filter(topic=data))
    return render(request,'page6.html',context={'objects':qs})

templates/page2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body>
        <div class="alert alert-primary" role="alert">
                <h1>Welcome to page 2</h1>
              </div>
    <h1>Welcome to page 2</h1>
    <h2>{{data}}</h2>
    <img src="{% static 'images/img.png' %}" alt="Image not found">
    <a href="{% url 'page1' %}" class="badge badge-primary">Page1</a>
</body>
</html>

templates/page3.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Topic</title>
</head>
<body>
    {% if objects %}
    <h1>Topic TABLE</h1>
        <table border="2pt">
            <thead>
                <th>Topic_Name</th>
            </thead>
            {% for obj in objects %}
            <tr>
                <td>{{obj.topic}}</td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
    <h1>Data Not found</h1>
    {% endif %}
</body>
</html>

templates/page4.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Access_Records</title>
</head>
<body>
    {% if objects %}
    <h1>Access_Records TABLE</h1>
        <table border="2pt">
            <thead>
                <th>Webpage Name</th>
                <th>Accessed Date</th>
            </thead>
            {% for obj in objects %}
            <tr>
                <td>{{obj.name}}</td>
                <td>{{obj.date}}</td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
    <h1>Data Not found</h1>
    {% endif %}
</body>
</html>

templates/page5.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Forms</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body>
    <h1>Forms Demonstration</h1>
    <form action="{% url 'myapp:display' %}" method="POST">
        {% csrf_token %}
        {% if objects %}
        <label for="topic">Topic Name : </label>
        <select name="topic" id="topic">
            {% for obj in objects %}
            <option value="{{obj.topic}}">{{obj.topic}}</option>
            {% endfor %}
        </select>
        {% endif %}
        <input type="submit" value="Submit" class="btn btn-primary">
    </form>
</body>
</html>

templates/page6.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Webpages</title>
</head>
<body>
    {% if objects %}
    <h1>Webpages details</h1>
        <table border="2pt">
            <thead>
                <th>Topic Name</th>
                <th>Webpage Name</th>
                <th>URL</th>
            </thead>
            {% for obj in objects %}
            <tr>
                <td>{{obj.topic}}</td>
                <td>{{obj.name}}</td>
                <td>{{obj.url}}</td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
    <h1>Data Not found</h1>
    {% endif %}
</body>
</html>

templates/page7.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Forms</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body>
    <h1>Forms Demonstration</h1>
    <form action="{% url 'myapp:display' %}" method="POST">
        {% csrf_token %}
        {% if objects %}
            {% for obj in objects %}
            <label for="t1">{{obj.topic}}</label>
        <input type="radio" name="topic" id="t1" value="{{obj.topic}}">
        <br>    
        {% endfor %}
        {% endif %}
        <input type="submit" value="Submit" class="btn btn-primary">
    </form>
</body>
</html>

templates/page8.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Forms</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body>
    <h1>Forms Demonstration</h1>
    <form action="{% url 'myapp:display' %}" method="POST">
        {% csrf_token %}
        {% if objects %}
            {% for obj in objects %}
            <label for="t1">{{obj.topic}}</label>
        <input type="checkbox" name="{{obj.topic}}" id="t1" value="{{obj.topic}}">
        <br>    
        {% endfor %}
        {% endif %}
        <input type="submit" value="Submit" class="btn btn-primary">
    </form>
</body>
</html>